apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-backend
spec:
  project: default
  source:
    repoURL: https://github.com/benjb59/deployment.git
    targetRevision: HEAD
    path: apps/demo-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-io1h80
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true